// frontendV1/src/components/ui/PasswordInput.jsx
import { useState } from "react";
import { Eye, EyeOff } from "lucide-react";

export default function PasswordInput({ className = "", ...props }) {
  const [visible, setVisible] = useState(false);
  const Icon = visible ? EyeOff : Eye;

  return (
    <div className={`password-input ${className}`.trim()}>
      <input {...props} type={visible ? "text" : "password"} />
      <button
        type="button"
        className="password-input__toggle"
        aria-label={visible ? "Hide password" : "Show password"}
        aria-pressed={visible}
        onClick={() => setVisible((current) => !current)}
      >
        <Icon aria-hidden="true" size={19} />
      </button>
    </div>
  );
}

// Dashboard/app/components/PasswordInput.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{
  modelValue?: string | number
}>(), {
  modelValue: "",
})

const emit = defineEmits<{
  "update:modelValue": [value: string | number]
}>()

const isVisible = ref(false)
</script>

<template>
  <UInput
    v-bind="$attrs"
    :model-value="props.modelValue"
    :type="isVisible ? 'text' : 'password'"
    @update:model-value="emit('update:modelValue', $event as string | number)"
  >
    <template #trailing>
      <UButton
        color="neutral"
        variant="ghost"
        size="xs"
        type="button"
        square
        :aria-label="isVisible ? 'Hide password' : 'Show password'"
        :aria-pressed="isVisible"
        :icon="isVisible ? 'i-lucide-eye-off' : 'i-lucide-eye'"
        @click="isVisible = !isVisible"
      />
    </template>
  </UInput>
</template>
